[window]
padding={x=10, y=10}
opacity=0.7

[font]
size=13.0

[font.normal]
family="Monaspace Neon Var"
style="Medium"

[font.italic]
family="Monaspace Radon Var"
style="Medium Italic"

[font.bold]
style="Bold"

